### ISSUE TITLE
DeGoogle links

### ISSUE THREAD

**Issue by farooqkz** [ivan-hc/bananahackers#2]
Many links are googlified which allows Google to track users in this way. I suggest degoogling them.

**Comment by ivan-hc** [comment]
This site was written using Google Sites, it is normal for this kind of link to be included (not counting links to Google Drive). Having brought the site to GitHub allows me not to have to comply with Google's guidelines, which all too often lead to the unmotivated blocking of bananahackers.net contents for all the users.

After having "downgraded" Google Sites just to a "tool" for the creation of this content, I am satisfied with the API in use, which however are even less subject to the power of Google given the new host on GitHub.

In fact, [the DuckDuckGo extension](https://duckduckgo.com/app?natb=v301-7__&cp=atbaoct) demonstrates a type B rating in comparison to the original version hosted by Google, which is graded between C and D, and that's enough for me.
There are also special extensions for the browser that prevent tracking (like this one for [Firefox](https://addons.mozilla.org/en-US/firefox/addon/dont-track-me-google1/) and [Chrome](https://chrome.google.com/webstore/detail/dont-track-me-google/gdbofhhdmcladcmmfjolgndfkpobecpg).

So the question is another: can you see [bananahackers.net](https://bananahackers.net) in your country without having to use a VPN?

**Comment by farooqkz** [comment]
I can access bananahackers.net without using a VPN. But my current complain is about something else. I'm talking about links like this:
```
https://www.google.com/url?q=https%3A%2F%2Fwww.facebook.com%2FBananaHackers-101263954558113&sa=D&sntz=1&usg=AFQjCNEfO6gjzMYITEafBIM4len_F2b25g
```

When users click on a link it should directly go to that link instead of going through Google first. Is it possible to do that in the first place using the tool you use to create the website? If not we've got to write a Github Actions workflow for this.

**Comment by ivan-hc** [comment]
Yes, I can edit these links. How many links did you find with this problem? Report them all to me and I will try to solve (if I have time).

**Comment by ivan-hc** [comment]
Just updated [the main page](https://ivan-hc.github.io/bananahackers/) and the [Contact us](https://ivan-hc.github.io/bananahackers/Contact%20us.html) page, all the links related to the communication channels and the subdomains (the various *.bananahackers.net) are fixed. All these links ARE NOT fixed in the menu (top-left side) and the PayPal and Github source in other pages in the footer, they are recursive.

Hope this can be enough... if not, I don't care. I don't want to manipulate the whole site again for these bullsh*ts!
The site helped a lot of people when it was on the  Google's domain, with at least 2000 hits per day, I don't think that people care about this problem right now that the site is safer (and always available, because this was been blocked a lot of time by Google, always for unknown reasons to me).

And honestly, I don't want to work on the site anymore, KaiOS is no longer part of my world, and bananahackers.net is just the contribution I made to the community when I was active within it, and it's perfect the way it is.
In fact, I recommend that you work on the [wiki](https://wiki.bananahackers.net/) instead, since you insisted so much on opening one when I was still active in the community, and leave bananahackers.net in this museum as an antique.

KaiOS 3.0 will be released soon, and it will not be a topic that I will cover.

I have other much more important commitments now, and if you would like to join my amateur works of my spare time, you can find me on other repositories of this account, for GNU / Linux related projects (like [this](https://github.com/ivan-hc/AM-application-manager)), there you're welcome.

Greetings.

**Comment by farooqkz** [comment]
> Just updated [the main page](https://ivan-hc.github.io/bananahackers/) and the [Contact us](https://ivan-hc.github.io/bananahackers/Contact%20us.html) page, all the links related to the communication channels and the subdomains (the various *.bananahackers.net) are fixed.
> 
> On the contrary, all these links ARE NOT been fixed in the menu (top-left side, from the green logo) and the PayPal and Github source in other pages in the footer, they are recursive.
> 
> Hope this can be enough... if not, I don't care. I don't want to manipulate the whole site again for these bullsh*ts! The site helped a lot of people when it was on the Google's domain, with at least 2000 hits per day, I don't think that people care about this problem right now that the site is safer (and always available, because this was been blocked a lot of time by Google, always for unknown reasons to me).
> 
> And honestly, I don't want to work on the site anymore, KaiOS is no longer part of my world, and bananahackers.net is just the contribution I made to the community when I was active within it, and it's perfect the way it is. In fact, I recommend that you work on the [wiki](https://wiki.bananahackers.net/) instead, since you insisted so much on opening one when I was still active in the community, and leave bananahackers.net in this museum as an antique.
> 
> KaiOS 3.0 will be released soon, and it will not be a topic that I will cover.
> 
> I have other much more important commitments now, and if you would like to join my amateur works of my spare time, you can find me on other repositories of this account, for GNU / Linux related projects (like [this](https://github.com/ivan-hc/AM-application-manager)), you're welcome.
> 
> Greetings.

You should not have edited the links, my idea was automation using Actions not manually editing. But it seems you are not much interested in any more change. So I'll leave it as it is.
